services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datastrom_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
